name: Check Uncovered Folders

on:
  push:
    branches: [ main, ci-automation, new-languages ]
  pull_request:
    branches: [ main ]

jobs:
  check-uncovered:
    name: Check Uncovered Folders
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run uncovered folders script
        run: |
          chmod +x ./list_uncovered_folders.sh
          ./list_uncovered_folders.sh