name: Test - C/C++

on:
  push:
    branches: [ main, ci-automation, new-languages ]
  pull_request:
    branches: [ main ]

jobs:
  cpp:
    name: Build and Test C/C++
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build (C - Make)
        run: |
          if [ -f c/Makefile ]; then (cd c && make); fi
      - name: Build (C++ - CMake)
        run: |
          if [ -f cpp/CMakeLists.txt ]; then mkdir -p cpp/build && cd cpp/build && cmake .. && cmake --build .; fi