name: Test - Rust

on:
  push:
    branches: [ main, ci-automation, new-languages ]
  pull_request:
    branches: [ main ]

jobs:
  rust:
    name: Build and Test Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: |
          if [ -f rust/Cargo.toml ]; then (cd rust && cargo build --workspace --all-targets); fi