name: Test Crystal

on:
  push:
    branches: [ main, ci-automation ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test Crystal
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Crystal from official repository
      run: |
        curl -fsSL https://crystal-lang.org/install.sh | bash

    - name: Run Crystal program
      run: |
        cd crystal/src
        crystal run main.cr