name: Test CSharp

on:
  push:
    branches: [ main, ci-automation ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test CSharp
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET
      run: |
        sudo apt update
        sudo apt install -y dotnet-sdk-6.0

    - name: Build and Test CSharp project
      run: |
        cd csharp
        dotnet build
        dotnet test