name: Node.js tests

on:
  push:
    branches: [ main, ci-automation, new-languages ]
  pull_request:
    branches: [ main ]

jobs:
  node:
    name: Node (Express & React)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & build node-express
        run: |
          if [ -f node-express/package.json ]; then \
            (cd node-express && if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ] || [ -f yarn.lock ]; then npm ci; else npm install; fi); fi
      - name: Install & build react-vite
        run: |
          if [ -f react-vite/package.json ]; then \
            (cd react-vite && if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ] || [ -f yarn.lock ]; then npm ci; else npm install; fi && npm run build --if-present); fi