name: Test Dart

on:
  push:
    branches: [ main, ci-automation ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test Dart
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dart
      run: |
        sudo apt update
        sudo apt install -y dart

    - name: Run Dart program
      run: |
        cd dart/bin
        dart run main.dart